{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "elodea.fullname" . }}
  labels:
    {{- include "elodea.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "elodea.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - port: 8080
      {{- with .Values.networkPolicy.ingressFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    - ports:
        - port: {{ .Values.metrics.port }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- with .Values.networkPolicy.egressTo }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
