// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"
)

const consumeLoginAttempt = `-- name: ConsumeLoginAttempt :one
DELETE FROM auth_login_attempts
WHERE state = $1 AND expires_at > NOW()
RETURNING nonce, code_verifier, return_to
`

type ConsumeLoginAttemptRow struct {
	Nonce        string `json:"nonce"`
	CodeVerifier string `json:"code_verifier"`
	ReturnTo     string `json:"return_to"`
}

// Single use: the row is deleted as it is read, so a replayed callback finds
// nothing. Expired rows never match.
func (q *Queries) ConsumeLoginAttempt(ctx context.Context, state string) (ConsumeLoginAttemptRow, error) {
	row := q.db.QueryRowContext(ctx, consumeLoginAttempt, state)
	var i ConsumeLoginAttemptRow
	err := row.Scan(&i.Nonce, &i.CodeVerifier, &i.ReturnTo)
	return i, err
}

const createLoginAttempt = `-- name: CreateLoginAttempt :exec
INSERT INTO auth_login_attempts (state, nonce, code_verifier, return_to, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateLoginAttemptParams struct {
	State        string    `json:"state"`
	Nonce        string    `json:"nonce"`
	CodeVerifier string    `json:"code_verifier"`
	ReturnTo     string    `json:"return_to"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, createLoginAttempt,
		arg.State,
		arg.Nonce,
		arg.CodeVerifier,
		arg.ReturnTo,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id_hash, subject, email, role, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	IDHash    string    `json:"id_hash"`
	Subject   string    `json:"subject"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.IDHash,
		arg.Subject,
		arg.Email,
		arg.Role,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredLoginAttempts = `-- name: DeleteExpiredLoginAttempts :exec
DELETE FROM auth_login_attempts WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredLoginAttempts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredLoginAttempts)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id_hash, subject, email, role, created_at, expires_at, last_seen_at
FROM sessions
WHERE id_hash = $1 AND revoked_at IS NULL AND expires_at > NOW() AND last_seen_at > $2
`

type GetActiveSessionParams struct {
	IDHash     string    `json:"id_hash"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

type GetActiveSessionRow struct {
	IDHash     string    `json:"id_hash"`
	Subject    string    `json:"subject"`
	Email      string    `json:"email"`
	Role       string    `json:"role"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

// Active means not revoked, before its absolute expiry, and seen within the
// idle window ($2 is the idle cutoff).
func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (GetActiveSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveSession, arg.IDHash, arg.LastSeenAt)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.IDHash,
		&i.Subject,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = NOW()
WHERE id_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, idHash string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, idHash)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = NOW()
WHERE id_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, idHash string) error {
	_, err := q.db.ExecContext(ctx, touchSession, idHash)
	return err
}
