// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"
	"time"
)

const countTodayActions = `-- name: CountTodayActions :one
SELECT COUNT(*) FROM ledger WHERE timestamp >= CURRENT_DATE
`

func (q *Queries) CountTodayActions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodayActions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodayViolations = `-- name: CountTodayViolations :one
SELECT COUNT(*) FROM ledger WHERE timestamp >= CURRENT_DATE AND decision IN ('deny', 'quarantine')
`

func (q *Queries) CountTodayViolations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodayViolations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLatestLedgerEntry = `-- name: GetLatestLedgerEntry :one
SELECT COALESCE(hash, ''), COALESCE(seq_num, 0)
FROM ledger ORDER BY seq_num DESC LIMIT 1 FOR UPDATE
`

type GetLatestLedgerEntryRow struct {
	Hash   string `json:"hash"`
	SeqNum int64  `json:"seq_num"`
}

func (q *Queries) GetLatestLedgerEntry(ctx context.Context) (GetLatestLedgerEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestLedgerEntry)
	var i GetLatestLedgerEntryRow
	err := row.Scan(&i.Hash, &i.SeqNum)
	return i, err
}

const getLedgerEntry = `-- name: GetLedgerEntry :one
SELECT seq_num, timestamp, agent, tool, decision, policy_rule, payload_hash, prev_hash, hash, request_id
FROM ledger WHERE seq_num = $1
`

func (q *Queries) GetLedgerEntry(ctx context.Context, seqNum int64) (Ledger, error) {
	row := q.db.QueryRowContext(ctx, getLedgerEntry, seqNum)
	var i Ledger
	err := row.Scan(
		&i.SeqNum,
		&i.Timestamp,
		&i.Agent,
		&i.Tool,
		&i.Decision,
		&i.PolicyRule,
		&i.PayloadHash,
		&i.PrevHash,
		&i.Hash,
		&i.RequestID,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger (seq_num, timestamp, agent, tool, decision, policy_rule, payload_hash, prev_hash, hash, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertLedgerEntryParams struct {
	SeqNum      int64     `json:"seq_num"`
	Timestamp   time.Time `json:"timestamp"`
	Agent       string    `json:"agent"`
	Tool        string    `json:"tool"`
	Decision    string    `json:"decision"`
	PolicyRule  string    `json:"policy_rule"`
	PayloadHash string    `json:"payload_hash"`
	PrevHash    string    `json:"prev_hash"`
	Hash        string    `json:"hash"`
	RequestID   string    `json:"request_id"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertLedgerEntry,
		arg.SeqNum,
		arg.Timestamp,
		arg.Agent,
		arg.Tool,
		arg.Decision,
		arg.PolicyRule,
		arg.PayloadHash,
		arg.PrevHash,
		arg.Hash,
		arg.RequestID,
	)
	return err
}

const listLedgerEntriesAsc = `-- name: ListLedgerEntriesAsc :many
SELECT seq_num, timestamp, agent, tool, decision, policy_rule, payload_hash, prev_hash, hash, request_id
FROM ledger ORDER BY seq_num ASC
`

func (q *Queries) ListLedgerEntriesAsc(ctx context.Context) ([]Ledger, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEntriesAsc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ledger{}
	for rows.Next() {
		var i Ledger
		if err := rows.Scan(
			&i.SeqNum,
			&i.Timestamp,
			&i.Agent,
			&i.Tool,
			&i.Decision,
			&i.PolicyRule,
			&i.PayloadHash,
			&i.PrevHash,
			&i.Hash,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLedgerEntries = `-- name: ListRecentLedgerEntries :many
SELECT seq_num, timestamp, agent, tool, decision, policy_rule, payload_hash, prev_hash, hash, request_id
FROM ledger ORDER BY seq_num DESC LIMIT 100
`

func (q *Queries) ListRecentLedgerEntries(ctx context.Context) ([]Ledger, error) {
	rows, err := q.db.QueryContext(ctx, listRecentLedgerEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ledger{}
	for rows.Next() {
		var i Ledger
		if err := rows.Scan(
			&i.SeqNum,
			&i.Timestamp,
			&i.Agent,
			&i.Tool,
			&i.Decision,
			&i.PolicyRule,
			&i.PayloadHash,
			&i.PrevHash,
			&i.Hash,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
