// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Ledger struct {
	SeqNum      int64     `json:"seq_num"`
	Timestamp   time.Time `json:"timestamp"`
	Agent       string    `json:"agent"`
	Tool        string    `json:"tool"`
	Decision    string    `json:"decision"`
	PolicyRule  string    `json:"policy_rule"`
	PayloadHash string    `json:"payload_hash"`
	PrevHash    string    `json:"prev_hash"`
	Hash        string    `json:"hash"`
	RequestID   string    `json:"request_id"`
}

type Quarantine struct {
	ID         uuid.UUID      `json:"id"`
	AgentID    string         `json:"agent_id"`
	ToolName   string         `json:"tool_name"`
	Payload    []byte         `json:"payload"`
	Status     string         `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
	ResolvedAt sql.NullTime   `json:"resolved_at"`
	ResolvedBy sql.NullString `json:"resolved_by"`
	Reason     sql.NullString `json:"reason"`
	Attempts   int32          `json:"attempts"`
	ReplayedAt sql.NullTime   `json:"replayed_at"`
}
