// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const claimDueNotifications = `-- name: ClaimDueNotifications :many
UPDATE notification_outbox o
SET attempts = o.attempts + 1,
    next_attempt_at = NOW() + INTERVAL '2 minutes'
FROM (
    SELECT quarantine_id, channel
    FROM notification_outbox
    WHERE delivered_at IS NULL
      AND attempts < $1::int
      AND next_attempt_at <= NOW()
    ORDER BY created_at
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
) due
WHERE o.quarantine_id = due.quarantine_id AND o.channel = due.channel
RETURNING o.quarantine_id::text AS quarantine_id, o.channel, o.attempts
`

type ClaimDueNotificationsParams struct {
	MaxAttempts int32 `json:"max_attempts"`
	BatchSize   int32 `json:"batch_size"`
}

type ClaimDueNotificationsRow struct {
	QuarantineID string `json:"quarantine_id"`
	Channel      string `json:"channel"`
	Attempts     int32  `json:"attempts"`
}

// Leases due rows for a few minutes while they are sent. A replica that
// crashes mid-send leaves the lease to expire, and the row is retried.
func (q *Queries) ClaimDueNotifications(ctx context.Context, arg ClaimDueNotificationsParams) ([]ClaimDueNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, claimDueNotifications, arg.MaxAttempts, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueNotificationsRow{}
	for rows.Next() {
		var i ClaimDueNotificationsRow
		if err := rows.Scan(&i.QuarantineID, &i.Channel, &i.Attempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueHeldNotifications = `-- name: EnqueueHeldNotifications :exec
INSERT INTO notification_outbox (quarantine_id, channel)
SELECT q.id, ch
FROM quarantine q CROSS JOIN unnest($1::text[]) AS ch
WHERE q.status = 'pending'
ON CONFLICT DO NOTHING
`

// Queue every pending held action for every configured channel. Rows that
// already exist are left alone, so this is safe to run on every tick.
func (q *Queries) EnqueueHeldNotifications(ctx context.Context, channels []string) error {
	_, err := q.db.ExecContext(ctx, enqueueHeldNotifications, pq.Array(channels))
	return err
}

const markNotificationDelivered = `-- name: MarkNotificationDelivered :exec
UPDATE notification_outbox
SET delivered_at = NOW(), last_error = ''
WHERE quarantine_id = $1::uuid AND channel = $2
`

type MarkNotificationDeliveredParams struct {
	QuarantineID uuid.UUID `json:"quarantine_id"`
	Channel      string    `json:"channel"`
}

func (q *Queries) MarkNotificationDelivered(ctx context.Context, arg MarkNotificationDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationDelivered, arg.QuarantineID, arg.Channel)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notification_outbox
SET next_attempt_at = $1, last_error = $2
WHERE quarantine_id = $3::uuid AND channel = $4
`

type MarkNotificationFailedParams struct {
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
	QuarantineID  uuid.UUID `json:"quarantine_id"`
	Channel       string    `json:"channel"`
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationFailed,
		arg.NextAttemptAt,
		arg.LastError,
		arg.QuarantineID,
		arg.Channel,
	)
	return err
}
