// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quarantine.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const approveQuarantineEntry = `-- name: ApproveQuarantineEntry :execresult
UPDATE quarantine SET status = $1, resolved_at = $2, resolved_by = $3, attempts = 0
WHERE id = $4::uuid AND status IN ('pending', 'replay_failed')
`

type ApproveQuarantineEntryParams struct {
	Status     string         `json:"status"`
	ResolvedAt sql.NullTime   `json:"resolved_at"`
	ResolvedBy sql.NullString `json:"resolved_by"`
	ID         uuid.UUID      `json:"id"`
}

func (q *Queries) ApproveQuarantineEntry(ctx context.Context, arg ApproveQuarantineEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, approveQuarantineEntry,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.ID,
	)
}

const claimApprovedForReplay = `-- name: ClaimApprovedForReplay :many
UPDATE quarantine SET status = 'replaying'
WHERE id IN (
    SELECT id FROM quarantine WHERE status = 'approved' ORDER BY created_at LIMIT $1
)
RETURNING id, agent_id, tool_name, payload, status, created_at, resolved_at, resolved_by, reason, attempts, replayed_at
`

func (q *Queries) ClaimApprovedForReplay(ctx context.Context, limit int32) ([]Quarantine, error) {
	rows, err := q.db.QueryContext(ctx, claimApprovedForReplay, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quarantine{}
	for rows.Next() {
		var i Quarantine
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ToolName,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.Reason,
			&i.Attempts,
			&i.ReplayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createQuarantineEntry = `-- name: CreateQuarantineEntry :one
INSERT INTO quarantine (agent_id, tool_name, payload, status, created_at)
VALUES ($1, $2, $3, 'pending', $4) RETURNING id::text
`

type CreateQuarantineEntryParams struct {
	AgentID   string    `json:"agent_id"`
	ToolName  string    `json:"tool_name"`
	Payload   []byte    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateQuarantineEntry(ctx context.Context, arg CreateQuarantineEntryParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createQuarantineEntry,
		arg.AgentID,
		arg.ToolName,
		arg.Payload,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const denyQuarantineEntry = `-- name: DenyQuarantineEntry :execresult
UPDATE quarantine SET status = $1, resolved_at = $2, resolved_by = $3, reason = $4
WHERE id = $5::uuid AND status IN ('pending', 'replay_failed')
`

type DenyQuarantineEntryParams struct {
	Status     string         `json:"status"`
	ResolvedAt sql.NullTime   `json:"resolved_at"`
	ResolvedBy sql.NullString `json:"resolved_by"`
	Reason     sql.NullString `json:"reason"`
	ID         uuid.UUID      `json:"id"`
}

func (q *Queries) DenyQuarantineEntry(ctx context.Context, arg DenyQuarantineEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, denyQuarantineEntry,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.Reason,
		arg.ID,
	)
}

const getQuarantineEntry = `-- name: GetQuarantineEntry :one
SELECT id, agent_id, tool_name, payload, status, created_at, resolved_at, resolved_by, reason, attempts, replayed_at FROM quarantine WHERE id = $1::uuid
`

func (q *Queries) GetQuarantineEntry(ctx context.Context, dollar_1 uuid.UUID) (Quarantine, error) {
	row := q.db.QueryRowContext(ctx, getQuarantineEntry, dollar_1)
	var i Quarantine
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ToolName,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Reason,
		&i.Attempts,
		&i.ReplayedAt,
	)
	return i, err
}

const getQuarantineEntryForReplay = `-- name: GetQuarantineEntryForReplay :one
SELECT id, agent_id, tool_name, payload, status, created_at, resolved_at, resolved_by, reason, attempts, replayed_at FROM quarantine WHERE id = $1::uuid
`

func (q *Queries) GetQuarantineEntryForReplay(ctx context.Context, dollar_1 uuid.UUID) (Quarantine, error) {
	row := q.db.QueryRowContext(ctx, getQuarantineEntryForReplay, dollar_1)
	var i Quarantine
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ToolName,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Reason,
		&i.Attempts,
		&i.ReplayedAt,
	)
	return i, err
}

const listQuarantineByStatus = `-- name: ListQuarantineByStatus :many
SELECT id, agent_id, tool_name, payload, status, created_at, resolved_at, resolved_by, reason, attempts, replayed_at FROM quarantine WHERE status = $1
`

func (q *Queries) ListQuarantineByStatus(ctx context.Context, status string) ([]Quarantine, error) {
	rows, err := q.db.QueryContext(ctx, listQuarantineByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quarantine{}
	for rows.Next() {
		var i Quarantine
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ToolName,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.Reason,
			&i.Attempts,
			&i.ReplayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReplayFailed = `-- name: MarkReplayFailed :exec
UPDATE quarantine SET status = 'replay_failed' WHERE id = $1::uuid AND status = 'approved'
`

func (q *Queries) MarkReplayFailed(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markReplayFailed, dollar_1)
	return err
}

const markReplayed = `-- name: MarkReplayed :exec
UPDATE quarantine SET status = 'replayed', replayed_at = NOW(), attempts = attempts + 1
WHERE id = $1::uuid AND status = 'replaying'
`

func (q *Queries) MarkReplayed(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markReplayed, dollar_1)
	return err
}

const recoverStuckReplays = `-- name: RecoverStuckReplays :execrows
UPDATE quarantine SET status = 'approved' WHERE status = 'replaying'
`

func (q *Queries) RecoverStuckReplays(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, recoverStuckReplays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const returnToApproved = `-- name: ReturnToApproved :exec
UPDATE quarantine SET status = 'approved', attempts = attempts + 1
WHERE id = $1::uuid AND status = 'replaying'
`

func (q *Queries) ReturnToApproved(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, returnToApproved, dollar_1)
	return err
}
