// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	ApproveQuarantineEntry(ctx context.Context, arg ApproveQuarantineEntryParams) (sql.Result, error)
	ClaimApprovedForReplay(ctx context.Context, limit int32) ([]Quarantine, error)
	CountTodayActions(ctx context.Context) (int64, error)
	CountTodayViolations(ctx context.Context) (int64, error)
	CreateQuarantineEntry(ctx context.Context, arg CreateQuarantineEntryParams) (string, error)
	DenyQuarantineEntry(ctx context.Context, arg DenyQuarantineEntryParams) (sql.Result, error)
	GetLatestLedgerEntry(ctx context.Context) (GetLatestLedgerEntryRow, error)
	GetLedgerEntry(ctx context.Context, seqNum int64) (Ledger, error)
	GetQuarantineEntry(ctx context.Context, dollar_1 uuid.UUID) (Quarantine, error)
	GetQuarantineEntryForReplay(ctx context.Context, dollar_1 uuid.UUID) (Quarantine, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error
	ListLedgerEntriesAsc(ctx context.Context) ([]Ledger, error)
	ListQuarantineByStatus(ctx context.Context, status string) ([]Quarantine, error)
	ListRecentLedgerEntries(ctx context.Context) ([]Ledger, error)
	// Guard must match the state the worker is in when it calls this: the entry
	// was claimed to 'replaying'. A guard on 'approved' here silently matches
	// zero rows, and the :execresult RowsAffected check in the Store is what
	// turns that silent no-op into an error instead of wedging the machine.
	MarkReplayFailed(ctx context.Context, dollar_1 uuid.UUID) (sql.Result, error)
	MarkReplayed(ctx context.Context, dollar_1 uuid.UUID) (sql.Result, error)
	RecoverStuckReplays(ctx context.Context) (int64, error)
	ReturnToApproved(ctx context.Context, dollar_1 uuid.UUID) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
