// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sql/*.sql
// database: postgresql

package db

import (
	"context"
	"database/sql"
	"time"
)

// ============================================================================
// Types
// ============================================================================

type LedgerEntry struct {
	SeqNum      int
	Timestamp   time.Time
	Agent       string
	Tool        string
	Decision    string
	PolicyRule  string
	PayloadHash string
	PrevHash    string
	Hash        string
}

type QuarantineEntry struct {
	ID         string
	AgentID    string
	ToolName   string
	Payload    []byte
	Status     string
	CreatedAt  time.Time
	ResolvedAt sql.NullTime
	ResolvedBy string
}

type LedgerStats struct {
	TotalActionsToday int
	PolicyViolations  int
}

// ============================================================================
// Interface
// ============================================================================

type Querier interface {
	// Ledger
	GetLatestLedgerEntry(ctx context.Context) (prevHash string, seqNum int, err error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error
	ListLedgerEntriesAsc(ctx context.Context) ([]LedgerEntry, error)
	ListRecentLedgerEntries(ctx context.Context) ([]LedgerEntry, error)
	CountTodayActions(ctx context.Context) (int, error)
	CountTodayViolations(ctx context.Context) (int, error)
	GetLedgerEntry(ctx context.Context, seqNum int) (LedgerEntry, error)

	// Quarantine
	CreateQuarantineEntry(ctx context.Context, arg CreateQuarantineEntryParams) (string, error)
	GetQuarantineEntry(ctx context.Context, id string) (QuarantineEntry, error)
	GetQuarantineEntryForReplay(ctx context.Context, id string) (QuarantineEntry, error)
	ListQuarantineByStatus(ctx context.Context, status string) ([]QuarantineEntry, error)
	ApproveQuarantineEntry(ctx context.Context, arg ApproveQuarantineEntryParams) (sql.Result, error)
	MarkReplayFailed(ctx context.Context, id string) error
	DenyQuarantineEntry(ctx context.Context, arg DenyQuarantineEntryParams) (sql.Result, error)

	// Transaction support for complex operations
	DB() *sql.DB
}

type InsertLedgerEntryParams struct {
	SeqNum      int
	Timestamp   time.Time
	Agent       string
	Tool        string
	Decision    string
	PolicyRule  string
	PayloadHash string
	PrevHash    string
	Hash        string
}

type CreateQuarantineEntryParams struct {
	AgentID   string
	ToolName  string
	Payload   []byte
	CreatedAt time.Time
}

type ApproveQuarantineEntryParams struct {
	Status     string
	ResolvedAt time.Time
	ResolvedBy string
	ID         string
}

type DenyQuarantineEntryParams struct {
	Status     string
	ResolvedAt time.Time
	ResolvedBy string
	Reason     string
	ID         string
}

// ============================================================================
// Implementation
// ============================================================================

type querier struct {
	db *sql.DB
}

func New(db *sql.DB) Querier {
	return &querier{db: db}
}

func (q *querier) DB() *sql.DB {
	return q.db
}

// ============================================================================
// Ledger
// ============================================================================

const getLatestLedgerEntry = `-- name: GetLatestLedgerEntry :one
SELECT COALESCE(hash, ''), COALESCE(seq_num, 0)
FROM ledger ORDER BY seq_num DESC LIMIT 1 FOR UPDATE
`

func (q *querier) GetLatestLedgerEntry(ctx context.Context) (prevHash string, seqNum int, err error) {
	err = q.db.QueryRowContext(ctx, getLatestLedgerEntry).Scan(&prevHash, &seqNum)
	return
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger (seq_num, timestamp, agent, tool, decision, policy_rule, payload_hash, prev_hash, hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

func (q *querier) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertLedgerEntry,
		arg.SeqNum, arg.Timestamp, arg.Agent, arg.Tool, arg.Decision,
		arg.PolicyRule, arg.PayloadHash, arg.PrevHash, arg.Hash,
	)
	return err
}

const listLedgerEntriesAsc = `-- name: ListLedgerEntriesAsc :many
SELECT seq_num, timestamp, agent, tool, decision, policy_rule, payload_hash, prev_hash, hash
FROM ledger ORDER BY seq_num ASC
`

func (q *querier) ListLedgerEntriesAsc(ctx context.Context) ([]LedgerEntry, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEntriesAsc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var entries []LedgerEntry
	for rows.Next() {
		var e LedgerEntry
		if err := rows.Scan(&e.SeqNum, &e.Timestamp, &e.Agent, &e.Tool, &e.Decision, &e.PolicyRule, &e.PayloadHash, &e.PrevHash, &e.Hash); err != nil {
			return nil, err
		}
		entries = append(entries, e)
	}
	return entries, rows.Err()
}

const listRecentLedgerEntries = `-- name: ListRecentLedgerEntries :many
SELECT seq_num, timestamp, agent, tool, decision, policy_rule, payload_hash, prev_hash, hash
FROM ledger ORDER BY seq_num DESC LIMIT 100
`

func (q *querier) ListRecentLedgerEntries(ctx context.Context) ([]LedgerEntry, error) {
	rows, err := q.db.QueryContext(ctx, listRecentLedgerEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var entries []LedgerEntry
	for rows.Next() {
		var e LedgerEntry
		if err := rows.Scan(&e.SeqNum, &e.Timestamp, &e.Agent, &e.Tool, &e.Decision, &e.PolicyRule, &e.PayloadHash, &e.PrevHash, &e.Hash); err != nil {
			return nil, err
		}
		entries = append(entries, e)
	}
	return entries, rows.Err()
}

const countTodayActions = `-- name: CountTodayActions :one
SELECT COUNT(*) FROM ledger WHERE timestamp >= CURRENT_DATE
`

func (q *querier) CountTodayActions(ctx context.Context) (int, error) {
	var count int
	err := q.db.QueryRowContext(ctx, countTodayActions).Scan(&count)
	return count, err
}

const countTodayViolations = `-- name: CountTodayViolations :one
SELECT COUNT(*) FROM ledger WHERE timestamp >= CURRENT_DATE AND decision IN ('deny', 'quarantine')
`

func (q *querier) CountTodayViolations(ctx context.Context) (int, error) {
	var count int
	err := q.db.QueryRowContext(ctx, countTodayViolations).Scan(&count)
	return count, err
}

const getLedgerEntry = `-- name: GetLedgerEntry :one
SELECT seq_num, timestamp, agent, tool, decision, policy_rule, payload_hash, prev_hash, hash
FROM ledger WHERE seq_num = $1
`

func (q *querier) GetLedgerEntry(ctx context.Context, seqNum int) (LedgerEntry, error) {
	var e LedgerEntry
	err := q.db.QueryRowContext(ctx, getLedgerEntry, seqNum).Scan(
		&e.SeqNum, &e.Timestamp, &e.Agent, &e.Tool, &e.Decision,
		&e.PolicyRule, &e.PayloadHash, &e.PrevHash, &e.Hash,
	)
	return e, err
}

// ============================================================================
// Quarantine
// ============================================================================

const createQuarantineEntry = `-- name: CreateQuarantineEntry :one
INSERT INTO quarantine (agent_id, tool_name, payload, status, created_at)
VALUES ($1, $2, $3, 'pending', $4) RETURNING id::text
`

func (q *querier) CreateQuarantineEntry(ctx context.Context, arg CreateQuarantineEntryParams) (string, error) {
	var id string
	err := q.db.QueryRowContext(ctx, createQuarantineEntry,
		arg.AgentID, arg.ToolName, arg.Payload, arg.CreatedAt,
	).Scan(&id)
	return id, err
}

const getQuarantineEntry = `-- name: GetQuarantineEntry :one
SELECT id::text, COALESCE(agent_id, ''), COALESCE(tool_name, ''), payload, status, created_at, resolved_at, COALESCE(resolved_by, '')
FROM quarantine WHERE id = $1
`

func (q *querier) GetQuarantineEntry(ctx context.Context, id string) (QuarantineEntry, error) {
	var e QuarantineEntry
	err := q.db.QueryRowContext(ctx, getQuarantineEntry, id).Scan(
		&e.ID, &e.AgentID, &e.ToolName, &e.Payload, &e.Status,
		&e.CreatedAt, &e.ResolvedAt, &e.ResolvedBy,
	)
	return e, err
}

const getQuarantineEntryForReplay = `-- name: GetQuarantineEntryForReplay :one
SELECT id::text, COALESCE(agent_id, ''), COALESCE(tool_name, ''), payload, status, created_at, resolved_at, COALESCE(resolved_by, '')
FROM quarantine WHERE id = $1
`

func (q *querier) GetQuarantineEntryForReplay(ctx context.Context, id string) (QuarantineEntry, error) {
	var e QuarantineEntry
	err := q.db.QueryRowContext(ctx, getQuarantineEntryForReplay, id).Scan(
		&e.ID, &e.AgentID, &e.ToolName, &e.Payload, &e.Status,
		&e.CreatedAt, &e.ResolvedAt, &e.ResolvedBy,
	)
	return e, err
}

const listQuarantineByStatus = `-- name: ListQuarantineByStatus :many
SELECT id::text, COALESCE(agent_id, ''), COALESCE(tool_name, ''), payload, status, created_at, resolved_at, COALESCE(resolved_by, '')
FROM quarantine WHERE status = $1
`

func (q *querier) ListQuarantineByStatus(ctx context.Context, status string) ([]QuarantineEntry, error) {
	rows, err := q.db.QueryContext(ctx, listQuarantineByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var entries []QuarantineEntry
	for rows.Next() {
		var e QuarantineEntry
		if err := rows.Scan(&e.ID, &e.AgentID, &e.ToolName, &e.Payload, &e.Status, &e.CreatedAt, &e.ResolvedAt, &e.ResolvedBy); err != nil {
			return nil, err
		}
		entries = append(entries, e)
	}
	return entries, rows.Err()
}

const approveQuarantineEntry = `-- name: ApproveQuarantineEntry :execresult
UPDATE quarantine SET status = $1, resolved_at = $2, resolved_by = $3
WHERE id = $4 AND status IN ('pending', 'replay_failed')
`

func (q *querier) ApproveQuarantineEntry(ctx context.Context, arg ApproveQuarantineEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, approveQuarantineEntry,
		arg.Status, arg.ResolvedAt, arg.ResolvedBy, arg.ID,
	)
}

const markReplayFailed = `-- name: MarkReplayFailed :exec
UPDATE quarantine SET status = 'replay_failed' WHERE id = $1 AND status = 'approved'
`

func (q *querier) MarkReplayFailed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markReplayFailed, id)
	return err
}

const denyQuarantineEntry = `-- name: DenyQuarantineEntry :execresult
UPDATE quarantine SET status = $1, resolved_at = $2, resolved_by = $3, reason = $4
WHERE id = $5 AND status IN ('pending', 'replay_failed')
`

func (q *querier) DenyQuarantineEntry(ctx context.Context, arg DenyQuarantineEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, denyQuarantineEntry,
		arg.Status, arg.ResolvedAt, arg.ResolvedBy, arg.Reason, arg.ID,
	)
}